[phases.setup]
nixPkgs = ["go", "gcc", "sqlite"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -o server ./cmd/server"]

[start]
cmd = "./server"

[variables]
GOOS = "linux"
GOARCH = "amd64"
CGO_ENABLED = "1" 