[phases.setup]
nixPkgs = ['go', 'gcc']

[phases.install]
cmds = ['go mod download']

[phases.build]
cmds = ['go build -o admoai ./cmd/server/main.go']

[start]
cmd = './admoai'

[variables]
GO_ENV = 'production'
CGO_ENABLED = '0'

[deploy]
startCommand = './admoai'
healthcheckPath = '/health'
healthcheckTimeout = 100
restartPolicyType = 'on-failure'
restartPolicyMaxRetries = 10 
